name: env_concat
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python >= 3.11.0
  - pandas >= 2.2.0
  - numpy
  - xlrd
  - typer >= 0.16.0
  - openpyxl
  - pep8
  - pylint
  - pytest
  - pytest-cov
  - pip
  - ruff
  - pre-commit
