name: env_concat
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python >= 3.13.0
  - pandas >= 2.2.0 
  - xlrd
  - typer >= 0.16.0
  - openpyxl
  - pep8
  - pylint
  - pytest
  - pytest-cov
  - pip
