name: Run Python Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: env_concat

      - name: Install pip dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .

      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          conda activate env_concat
          pytest tests --cov=files2db --cov-report=xml --cov-report=term-missing

      - name: Run CLI help test
        run: files2db --help

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          files: codecov/test-results-action@v1
          flags: unittests # optional
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)
