name: Run Python Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run all unittests and generate coverage report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: env_concat

      - name: Install pip dependencies
        run: pip install -e .

      - run: pytest tests

  coverage:
    name: Coverage report (latest Python only)
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: 3.14
          activate-environment: env_concat
          auto-activate-base: false

      - run: pip install -e .

      - run: pytest tests --cov=files2db --cov-report=xml:coverage.xml

      - uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
